name: Auto Sync with Main Branch

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  auto-sync:
    name: Auto Sync with Main Branch
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      - name: Fetch all branches
        run: git fetch --all

      - name: Delete bot-created branches
        run: | 
          echo "Finding all branches created by the bot..."
          if [ -z $(git branch -r | grep -E 'origin/feature/.*-sync-with-main-created-by-bot')]; then
            echo "No bot-created branches found."
          else
            echo "Bot-created branches found:"
            BOT_BRANCHES=$(git branch -r | grep -E 'origin/feature/.*-sync-with-main-created-by-bot')
            echo "$BOT_BRANCHES"
            for branch in $BOT_BRANCHES; do
              echo "Deleting branch: $branch"
              BRANCH_TO_DELETE=${branch#origin/}
              git push origin --delete $BRANCH_TO_DELETE
            done
          fi          

      - name: Get active Epic branches
        id: get_active_epic_branches
        run: |
          current_date=$(date +%s)
          one_week_ago=$(date -d '1 week ago' +%s)

          branches=()

          echo "Script Log: Listing all remote branches that start with 'feature/main/' and checking their last commit date..."
          EPIC_BRANCHES=$(git for-each-ref --sort=-committerdate refs/remotes/ --format='%(refname:short)' | grep '^origin/feature/main/')
          echo "Script log: Branches updated within the last week:"
          for branch in $EPIC_BRANCHES; do
            commit_date=$(git log -1 --format=%ct $branch)
            if [ $commit_date -ge $one_week_ago ]; then    
              branches+=("$branch")
              echo "$branch"
            fi
          done

          echo "active_branches=${branches[@]}" >> $GITHUB_OUTPUT
        shell: bash

      - name: Get latest changes from main
        run: |
          git checkout main
          git pull origin main
          echo "Script log: Pulled latest changes from main"

      